public class WithoutException {
public static void main(String[] args)
throws ArrayIndexOutOfBoundsException {
// int a=10;
// int b=0;
// int result=a/b;
// System.out.println("The result
is"+result);
try {
int a=10;
int b=0;
int result=a/b;
int arr[]= {1,2,3,4};
arr[5]=6;
System.out.println("The result
is"+result);
System.out.println("The result
is"+arr[5]);
}
catch(ArithmeticException e) {
System.out.println("A number
cannot be divided by zero");
}
catch(Exception e) {
System.out.println("Given array
size is not existing");
}
}
}
—-----------------------------------
//custom exception
public class MyException extends Exception{
public MyException(String mesg) {
super(mesg);
}
}
public class ValidateAge {
public static void validateAge(int age)
throws MyException,ArithmeticException {
if(age<0) {
throw new MyException("The
entered age is not valid");
}
else {
System.out.println("The age is
valid");
}
}
}
—-----------------------------------------
public class MyExceptionMain {
public static void main(String[] args)
throws ArithmeticException, MyException {
 ValidateAge.validateAge(12);
}
}
